/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRiwayatAbsenRouteImport } from './routes/_authenticated/riwayat-absen'
import { Route as AuthenticatedPengumumanRouteImport } from './routes/_authenticated/pengumuman'
import { Route as AuthenticatedPengajuanIzinRouteImport } from './routes/_authenticated/pengajuan-izin'
import { Route as AuthenticatedLainnyaRouteImport } from './routes/_authenticated/lainnya'
import { Route as AuthenticatedInformasiDataDiriRouteImport } from './routes/_authenticated/informasi-data-diri'
import { Route as AuthenticatedInfoRouteImport } from './routes/_authenticated/info'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckAbsenRouteImport } from './routes/_authenticated/check-absen'
import { Route as AuthenticatedAkunRouteImport } from './routes/_authenticated/akun'
import { Route as AuthenticatedAbsenStaffTerkaitRouteImport } from './routes/_authenticated/absen-staff-terkait'
import { Route as AuthenticatedAbsenLemburRouteImport } from './routes/_authenticated/absen-lembur'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiwayatAbsenRoute =
  AuthenticatedRiwayatAbsenRouteImport.update({
    id: '/riwayat-absen',
    path: '/riwayat-absen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengumumanRoute = AuthenticatedPengumumanRouteImport.update({
  id: '/pengumuman',
  path: '/pengumuman',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPengajuanIzinRoute =
  AuthenticatedPengajuanIzinRouteImport.update({
    id: '/pengajuan-izin',
    path: '/pengajuan-izin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLainnyaRoute = AuthenticatedLainnyaRouteImport.update({
  id: '/lainnya',
  path: '/lainnya',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInformasiDataDiriRoute =
  AuthenticatedInformasiDataDiriRouteImport.update({
    id: '/informasi-data-diri',
    path: '/informasi-data-diri',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInfoRoute = AuthenticatedInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckAbsenRoute = AuthenticatedCheckAbsenRouteImport.update({
  id: '/check-absen',
  path: '/check-absen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAkunRoute = AuthenticatedAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAbsenStaffTerkaitRoute =
  AuthenticatedAbsenStaffTerkaitRouteImport.update({
    id: '/absen-staff-terkait',
    path: '/absen-staff-terkait',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAbsenLemburRoute =
  AuthenticatedAbsenLemburRouteImport.update({
    id: '/absen-lembur',
    path: '/absen-lembur',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/absen-lembur': typeof AuthenticatedAbsenLemburRoute
  '/absen-staff-terkait': typeof AuthenticatedAbsenStaffTerkaitRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/check-absen': typeof AuthenticatedCheckAbsenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/info': typeof AuthenticatedInfoRoute
  '/informasi-data-diri': typeof AuthenticatedInformasiDataDiriRoute
  '/lainnya': typeof AuthenticatedLainnyaRoute
  '/pengajuan-izin': typeof AuthenticatedPengajuanIzinRoute
  '/pengumuman': typeof AuthenticatedPengumumanRoute
  '/riwayat-absen': typeof AuthenticatedRiwayatAbsenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/absen-lembur': typeof AuthenticatedAbsenLemburRoute
  '/absen-staff-terkait': typeof AuthenticatedAbsenStaffTerkaitRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/check-absen': typeof AuthenticatedCheckAbsenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/info': typeof AuthenticatedInfoRoute
  '/informasi-data-diri': typeof AuthenticatedInformasiDataDiriRoute
  '/lainnya': typeof AuthenticatedLainnyaRoute
  '/pengajuan-izin': typeof AuthenticatedPengajuanIzinRoute
  '/pengumuman': typeof AuthenticatedPengumumanRoute
  '/riwayat-absen': typeof AuthenticatedRiwayatAbsenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_authenticated/absen-lembur': typeof AuthenticatedAbsenLemburRoute
  '/_authenticated/absen-staff-terkait': typeof AuthenticatedAbsenStaffTerkaitRoute
  '/_authenticated/akun': typeof AuthenticatedAkunRoute
  '/_authenticated/check-absen': typeof AuthenticatedCheckAbsenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/info': typeof AuthenticatedInfoRoute
  '/_authenticated/informasi-data-diri': typeof AuthenticatedInformasiDataDiriRoute
  '/_authenticated/lainnya': typeof AuthenticatedLainnyaRoute
  '/_authenticated/pengajuan-izin': typeof AuthenticatedPengajuanIzinRoute
  '/_authenticated/pengumuman': typeof AuthenticatedPengumumanRoute
  '/_authenticated/riwayat-absen': typeof AuthenticatedRiwayatAbsenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/absen-lembur'
    | '/absen-staff-terkait'
    | '/akun'
    | '/check-absen'
    | '/dashboard'
    | '/info'
    | '/informasi-data-diri'
    | '/lainnya'
    | '/pengajuan-izin'
    | '/pengumuman'
    | '/riwayat-absen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/absen-lembur'
    | '/absen-staff-terkait'
    | '/akun'
    | '/check-absen'
    | '/dashboard'
    | '/info'
    | '/informasi-data-diri'
    | '/lainnya'
    | '/pengajuan-izin'
    | '/pengumuman'
    | '/riwayat-absen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/_authenticated/absen-lembur'
    | '/_authenticated/absen-staff-terkait'
    | '/_authenticated/akun'
    | '/_authenticated/check-absen'
    | '/_authenticated/dashboard'
    | '/_authenticated/info'
    | '/_authenticated/informasi-data-diri'
    | '/_authenticated/lainnya'
    | '/_authenticated/pengajuan-izin'
    | '/_authenticated/pengumuman'
    | '/_authenticated/riwayat-absen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/riwayat-absen': {
      id: '/_authenticated/riwayat-absen'
      path: '/riwayat-absen'
      fullPath: '/riwayat-absen'
      preLoaderRoute: typeof AuthenticatedRiwayatAbsenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengumuman': {
      id: '/_authenticated/pengumuman'
      path: '/pengumuman'
      fullPath: '/pengumuman'
      preLoaderRoute: typeof AuthenticatedPengumumanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengajuan-izin': {
      id: '/_authenticated/pengajuan-izin'
      path: '/pengajuan-izin'
      fullPath: '/pengajuan-izin'
      preLoaderRoute: typeof AuthenticatedPengajuanIzinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lainnya': {
      id: '/_authenticated/lainnya'
      path: '/lainnya'
      fullPath: '/lainnya'
      preLoaderRoute: typeof AuthenticatedLainnyaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/informasi-data-diri': {
      id: '/_authenticated/informasi-data-diri'
      path: '/informasi-data-diri'
      fullPath: '/informasi-data-diri'
      preLoaderRoute: typeof AuthenticatedInformasiDataDiriRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/info': {
      id: '/_authenticated/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof AuthenticatedInfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/check-absen': {
      id: '/_authenticated/check-absen'
      path: '/check-absen'
      fullPath: '/check-absen'
      preLoaderRoute: typeof AuthenticatedCheckAbsenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/akun': {
      id: '/_authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AuthenticatedAkunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/absen-staff-terkait': {
      id: '/_authenticated/absen-staff-terkait'
      path: '/absen-staff-terkait'
      fullPath: '/absen-staff-terkait'
      preLoaderRoute: typeof AuthenticatedAbsenStaffTerkaitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/absen-lembur': {
      id: '/_authenticated/absen-lembur'
      path: '/absen-lembur'
      fullPath: '/absen-lembur'
      preLoaderRoute: typeof AuthenticatedAbsenLemburRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAbsenLemburRoute: typeof AuthenticatedAbsenLemburRoute
  AuthenticatedAbsenStaffTerkaitRoute: typeof AuthenticatedAbsenStaffTerkaitRoute
  AuthenticatedAkunRoute: typeof AuthenticatedAkunRoute
  AuthenticatedCheckAbsenRoute: typeof AuthenticatedCheckAbsenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInfoRoute: typeof AuthenticatedInfoRoute
  AuthenticatedInformasiDataDiriRoute: typeof AuthenticatedInformasiDataDiriRoute
  AuthenticatedLainnyaRoute: typeof AuthenticatedLainnyaRoute
  AuthenticatedPengajuanIzinRoute: typeof AuthenticatedPengajuanIzinRoute
  AuthenticatedPengumumanRoute: typeof AuthenticatedPengumumanRoute
  AuthenticatedRiwayatAbsenRoute: typeof AuthenticatedRiwayatAbsenRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAbsenLemburRoute: AuthenticatedAbsenLemburRoute,
  AuthenticatedAbsenStaffTerkaitRoute: AuthenticatedAbsenStaffTerkaitRoute,
  AuthenticatedAkunRoute: AuthenticatedAkunRoute,
  AuthenticatedCheckAbsenRoute: AuthenticatedCheckAbsenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInfoRoute: AuthenticatedInfoRoute,
  AuthenticatedInformasiDataDiriRoute: AuthenticatedInformasiDataDiriRoute,
  AuthenticatedLainnyaRoute: AuthenticatedLainnyaRoute,
  AuthenticatedPengajuanIzinRoute: AuthenticatedPengajuanIzinRoute,
  AuthenticatedPengumumanRoute: AuthenticatedPengumumanRoute,
  AuthenticatedRiwayatAbsenRoute: AuthenticatedRiwayatAbsenRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
